server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Persistent cache files written by cache-service
    location /data/ {
        alias /data/;
        add_header Cache-Control "public, max-age=300";
        try_files $uri =404;
    }

    # SPA fallback — all unknown paths return index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
